### ISSUE TITLE
Possible to add folders instead of hole disks?

### ISSUE THREAD

**Issue by HaShLo** [szatmary/PlotFS#14]
Hi again,

the project is very beautiful and nice, thank you for that. But my question is:

Can i add folders to plotfs instead of hole disks which will be formatted. Because i dont want to add the hole disk to plotfs but single folders which has the left space of the disk and its also separated from other files on disk.

Is that possible or can you make it possible :) ? 

Thank you

**Comment by johnathon-b** [comment]
That's not quiet how PlotFS works.

If you want to share a hard disk, instead, you should partition your disk to the size space you would like to allocate towards Plots. After, add the partition as a device to Chia. 

You can mount the PlotFS folder where ever you want. If you have a specific path that you prefer to have your plots, you can mount it at that location. 

```
Debian

sudo mount.plotfs /your/desired/location

```

**Comment by HaShLo** [comment]
> That's not quiet how PlotFS works.
> 
> If you want to share a hard disk, instead, you should partition your disk to the size space you would like to allocate towards Plots. After, add the partition as a device to Chia.
> 
> You can mount the PlotFS folder where ever you want. If you have a specific path that you prefer to have your plots, you can mount it at that location.
> 
> ```
> Debian
> 
> sudo mount.plotfs /your/desired/location
> ```

it would be very nice if plotfs could work also with just with folders, because i have disks these are not physically connected with my pc. I have disks in my network which are only mounted, so in that case create a new partition will not work. 

But also in that case i want to use all available space and want to share my plots to all my disks. This case with network disk and different harvesters is not a unusual case. everyone in chia make it on this way.

So it would be nice have the chance to work with mounts/folders. the mount for the plots is irrelevant i think or do i have thinking error ?

**Comment by johnathon-b** [comment]
PlotFS is a file system that is used with a disk or partition. Your network folders or other local folders exist on another file system, already. 

The advantage of PlotFS is that it will use each block of the drive or partition. That's not possible by pointing PlotFS at a folder. 

What exactly are you trying to accomplish with the use of PlotFS in your current scenario?

**Comment by HaShLo** [comment]
> PlotFS is a file system that is used with a disk or partition. Your network folders or other local folders exist on another file system, already. 
> 
> The advantage of PlotFS is that it will use each block of the drive or partition. That's not possible by pointing PlotFS at a folder. 
> 
> What exactly are you trying to accomplish with the use of PlotFS in your current scenario? 
> 
> 

to use all space on the disk, just like you wrote.  its not possible to read the blocks of a drive over the network? 

 I mean at the end the drives on my machine have the same linux standard fs as the machine in my network and it is in most cases the ext4 fs. The only difference is that is not phsically connected.

I dont understand where the problem is ^^ sorry.

**Comment by mrmsp** [comment]
PlotFS uses the raw sectors of the disk. Not files or folders.

The locations of those sectors are stored in a database on your OS drive (typically /var/local/plotfs). That is used to simulate a file at the mount point (typically /farm) for the Chia farmer to read. Thus no space is wasted on the plot drive with filesystem overhead.

Remote access via NFS/SMB is not designed for accessing raw sectors over the network, only files. iSCSI is for remote raw sectors.

Regardless, you should be using remote harvesters for network attached plots.

**Comment by szatmary** [comment]
This is not possible. You should use a harvester on the second machine.
