### ISSUE TITLE
wildcard globbing for add-plots

### ISSUE THREAD

**Issue by mower7** [szatmary/PlotFS#6]
Thanks for spending your time to make this cool filesystem.

I have an existing farm that has a large number of plots, and I have added some new disks to it, and have started to copy my existing plots to a PlotFs  that uses these new drives.  And then as I empty out an existing ext4 filesystem, I intend to move that device into the farm, and proceed to the next device.  But it seems the I need to call out the plots one at a time for the --add-plots function.  It sure would be nice if we could use a wildcard to be able to do multiple plots at a time, or alternatively to specify just a directory, and have it pull in all the plots in that directory.

Just a thought

**Comment by johnathon-b** [comment]
I got around this by writing a script to add one of my farms to plotfs. 

```

for f in $(find /mnt/plots/*/*.plot)
do
 
	echo "Moving - $f"
	plotfs --add_plot "$f" --remove_source
done

```

**Comment by szatmary** [comment]
Not a bad idea. I'll look into it.

**Comment by szatmary** [comment]
done
