### ISSUE TITLE
Transfer Speeds

### ISSUE THREAD

**Issue by johnathon-b** [szatmary/PlotFS#7]
I have large farms and migrating one to PlotFS. It's taking a long time to transfer the plots. I'm looking for efficiencies as I plan migrating some other environments. 

Are there specific limitations? I've tried to start multiple jobs to transfer from multiple drives but it made everything slower. 

Anyways to parallel transfers?

**Comment by szatmary** [comment]
Plots will always be written to the disk with the most free space. So if one disk has significantly more free space, all plots will be written to that disk. Once the disks are balanced it should parallelize across spindles.

**Comment by johnathon-b** [comment]
> 

Does the parallelize across spindles affect the blast radius of a drive dying?

**Comment by szatmary** [comment]
Sorry, I explained that poorly. Each plot will write to 1 spindle. To spread across spindles, you need to write multiple plots at the same time.

**Comment by johnathon-b** [comment]
Can confirm, this drastically sped up the transfers into PlotFS.

I use this one-liner to begin transfers based on how many disks I added to PlotFS.

```
# run 5 jobs parallel
find /bigpool/plot-storage/ -name "*.plot" | shuf | parallel --jobs 5 -I% --max-args 1 ' plotfs --add_plot % --remove_source'
```

In **iotop** I can see decent speeds considering I'm transferring from a ZFS pool.
